# Generated by Django 5.2.6 on 2025-09-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_full_name', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=150, unique=True)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('user_password', models.CharField(max_length=128)),
                ('user_type', models.CharField(max_length=50)),
                ('user_is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
