# Generated by Django 5.2.6 on 2025-09-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_user_name_users_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
