# Generated by Django 5.2.6 on 2025-12-05 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_category', models.CharField(choices=[('Building Construction', 'Building Construction'), ('Road Work', 'Road Work'), ('Interior Work', 'Interior Work'), ('Plumbing', 'Plumbing'), ('Electric Work', 'Electric Work'), ('Painting', 'Painting')], max_length=100)),
                ('budget_lakhs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_terms', models.CharField(choices=[('Milestone Based', 'Milestone Based'), ('Weekly Billing', 'Weekly Billing'), ('Monthly Billing', 'Monthly Billing')], max_length=50)),
                ('advance_payment', models.PositiveIntegerField(blank=True, null=True)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('deadline', models.DateField()),
                ('required_workers', models.PositiveIntegerField(blank=True, null=True)),
                ('required_skills', models.CharField(blank=True, max_length=255, null=True)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='project_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='project_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='contractor.contractorproject')),
            ],
        ),
    ]
