# Generated by Django 5.2.6 on 2025-12-05 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Builder', '0001_initial'),
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorproject',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='The_Builder.users'),
            preserve_default=False,
        ),
    ]
