# Generated by Django 5.2.6 on 2025-12-05 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0002_contractorproject_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contractorproject',
            old_name='budget_lakhs',
            new_name='budget',
        ),
    ]
