# Generated by Django 5.2.6 on 2026-01-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0003_rename_budget_lakhs_contractorproject_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractorproject',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
