# Generated by Django 5.2.6 on 2026-01-16 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0005_message'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='contractor__sender__906d64_idx',
            old_name='contractor_m_sender__idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='contractor__receive_297000_idx',
            old_name='contractor_m_receive_idx',
        ),
    ]
