# Generated by Django 5.2.6 on 2026-01-15 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('The_Builder', '0001_initial'),
        ('contractor', '0004_alter_contractorproject_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_years', models.PositiveIntegerField()),
                ('proposed_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estimated_duration', models.PositiveIntegerField(help_text='Duration in days')),
                ('machines_equipment', models.TextField()),
                ('why_select_you', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_applications', to='The_Builder.users')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='contractor.contractorproject')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('project', 'applicant')},
            },
        ),
    ]
