# Generated by Django 5.2.6 on 2025-09-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_lead',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('lead_name', models.CharField(max_length=100)),
                ('lead_email', models.EmailField(max_length=254)),
                ('lead_phone', models.CharField(max_length=15)),
                ('lead_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_full_name', models.CharField(max_length=100)),
                ('user_username', models.CharField(max_length=150)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('user_password', models.CharField(max_length=128)),
                ('user_address', models.TextField(blank=True, null=True)),
                ('user_city', models.CharField(blank=True, max_length=100, null=True)),
                ('user_state', models.CharField(blank=True, max_length=100, null=True)),
                ('user_zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('user_country', models.CharField(blank=True, max_length=100, null=True)),
                ('user_about', models.TextField(blank=True, null=True)),
                ('user_type', models.CharField(max_length=50)),
                ('user_is_active', models.BooleanField(default=True)),
                ('user_profile', models.CharField(blank=True, max_length=100, null=True)),
                ('user_profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
