# Generated by Django 5.2.6 on 2025-09-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
