# Generated by Django 5.2.6 on 2025-09-28 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Builder', '0002_users_user_profile_users_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_lead',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('lead_name', models.CharField(max_length=100)),
                ('lead_email', models.EmailField(max_length=254)),
                ('lead_phone', models.CharField(max_length=15)),
                ('lead_message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
