# Generated by Django 5.2.6 on 2025-09-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Builder', '0003_contact_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='user_zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
